### ISSUE TITLE
Failed to launch docker, no such file or directory

### ISSUE THREAD

**Issue by jmg1menez** [pboardman/starbound-docker#6]
When i create the docker container, after building the dockerfile without problem, i get this error :

Fatal Exception caught: (IOException) Error opening file '../mods/*.pak', error: No such file or directory

this is my first docker so probably im missing something, could someone guide me into fixing it?

**Comment by jmg1menez** [comment]
as i readed through the script, the folder for it is "/server/steamcmd/starbound/mods/*.pak" should i copy from my host machine, or it should download alone from the starbound_update.txt? 

will try deleting the whole "mods" lines, since is for testing and i dont have any mod installed

**Comment by pboardman** [comment]
Hello! You shouldn't have to copy anything from your host machine for it to work. When you ran the docker command (`docker run -d -p=21025:21025 -v=/path/to/starbound/data:/server/steamcmd/starbound STEAM_USERNAME=username STEAM_PASSWORD=password lacsap/starbound`) did you replace `username` and `password` with your steam account credentials? Also steamguard can't be activated on the account or steamCMD won't be able to authenticate you.

**Comment by blade1981m** [comment]
I am also having the same issue. I have ran the docker container with my own steam credentials and do not have steamguard activated on the account. Attaching screenshot of error.
![Starbound error](https://user-images.githubusercontent.com/4664148/69487154-d2651580-0e1a-11ea-97f8-2e24a32a0076.png)

**Comment by pboardman** [comment]
Looks like a file named `*.pak` was created in the mods directory during the installation, crashing the server on boot. I'll have to look at it more in depth but meanwhile I added a line removing the file if it exist before starting the server. should be up on Dockerhub now! Could you try it again and tell me if it fixed the issue for you?

**Comment by blade1981m** [comment]
Works perfectly. Thank you so much.

**Comment by pboardman** [comment]
Great! I'll close the issue then. If there is anything else feel free to reopen it (or open a new one).

**Comment by ju4nmg** [comment]
it is working now, thanks!
